version: "3.9"

services:
  # Laravel側 +++++++++++++++++++++++++++++++++++++++++++++++++
  laravel-app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: ./laravel-docker/app/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./laravel/:/laravel-app
  laravel-web:
    container_name: laravel-web
    build:
      context: .
      dockerfile: ./laravel-docker/web/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - laravel-app
    volumes:
      - ./laravel/:/laravel-app
  postgresql:
    container_name: postgresql
    build: 
      context: .
      dockerfile: ./laravel-docker/db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./laravel-docker/db/init:/docker-entrypoint-initdb.d
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always
  # Laravel側 +++++++++++++++++++++++++++++++++++++++++++++++++
  ruby-db:
    image: postgres
    container_name: ruby-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  ruby-app-web:
    container_name: ruby-app
    build:
      context: .
      dockerfile: ./ruby-docker/app/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./ruby-app:/ruby-app
    ports:
      - "3000:3000"
    depends_on:
      - ruby-db
volumes:
  postgres_volume: